In [58]:
#Instead of branchname I have used company as the name of list only affecting the column name 

from selenium import webdriver 
driver = webdriver.Chrome("C:\\Users\\NISHANT\\Desktop\\chromedriver_win32\\chromedriver.exe")
driver.get("https://channeli.in/placement/results/branch/")
driver.find_element_by_name("username").send_keys("Enrollment Number Here")
driver.find_element_by_name("password").send_keys("Password")
driver.find_element_by_id("sign_in_button").click()
company = []
selected = []

In [59]:
#reach a location from which data has to be extracted
rows = driver.find_element_by_tag_name('tbody').find_elements_by_tag_name('tr')
for row in rows:
    print(row.text)

1 MSc Applied Geology 2 View View
2 IMSc Applied Mathematics 11 View View
3 B.Arch. Architecture and Planning 13 View View
4 M.Arch. Architecture and Planning 10 View View
5 IDD B. Tech. (Chemical Engineering) and M. Tech. (Hydrocarbon Engineering) 11 View View
6 IDD B. Tech. (Computer Science & Engineering) and M. Tech. (Information Technology) 2 View View
7 IDD B. Tech. (Electrical Engineering) and M.Tech. (Power Electronics) 10 View View
8 IDD B. Tech. (Electronics & Communication Engineering) and M. Tech. (Wireless Communication) 15 View View
9 IDD B. Tech. (Process Engineering) and M.B.A. 9 View View
10 B.Tech. Biotechnology 14 View View
11 MSc Biotechnology 1 View View
12 M.Tech. CAD,CAM & Robotics 4 View View
13 B.Tech. Chemical Engineering 49 View View
14 IMSc Chemistry 2 View View
15 B.Tech. Civil Engineering 36 View View
16 IDD Civil Engineering with specialisation in Structures 5 View View
17 M.Tech. Communication Systems 2 View View
18 M.Tech. Computer Science & Engineering 36 View View
19 B.Tech. Computer Science and Engineering 69 View View
20 M.Tech. Electric Drives and Power Electronics 2 View View
21 B.Tech. Electrical Engineering 92 View View
22 B.Tech. Electronics & Communication Engineering 66 View View
23 IMT Geological Technology 12 View View
24 IMT Geophysical Technology 15 View View
25 MSc M.Sc. Mathematics 1 View View
26 M.Tech. Machine Design Engineering 4 View View
27 MBA Management and Business Administration 47 View View
28 MURP Master of Urban and Rural Planning 1 View View
29 B.Tech. Mechanical Engineering 38 View View
30 B.Tech. Metallurgical & Materials Engineering 37 View View
31 IDD Metallurgy Dual 7 View View
32 M.Tech. Micro Electronic and VLSI 4 View View
33 IMSc Physics 3 View View
34 B.Tech. Polymer Science and Technology 1 View View
35 M.Tech. Power System Engineering 3 View View
36 B.Tech. Production and Industrial Engineering 25 View View
37 M.Tech. Pulp & Paper Engineering 1 View View
38 M.Tech. RF and Microwave Engineering 2 View View
39 M.Tech. Solid State Electronic Materials 1 View View
40 M.Tech. Structural Dynamics 8 View View
41 M.Tech. Structural Engineering 4 View View
42 M.Tech. System and Control 1 View View
43 M.Tech. Thermal Engineering 1 View View
44 M.Tech. Transportation Engineering 2 View View

In [60]:
rows = driver.find_element_by_tag_name('tbody').find_elements_by_tag_name('tr')
for row in rows:
    print(row.text)
    k=row.find_elements_by_tag_name('td')
    for i in row.find_elements_by_tag_name('td'):
        print(i.text)

1 MSc Applied Geology 2 View View
1
MSc
Applied Geology
2
View
View
2 IMSc Applied Mathematics 11 View View
2
IMSc
Applied Mathematics
11
View
View
3 B.Arch. Architecture and Planning 13 View View
3
B.Arch.
Architecture and Planning
13
View
View
4 M.Arch. Architecture and Planning 10 View View
4
M.Arch.
Architecture and Planning
10
View
View
5 IDD B. Tech. (Chemical Engineering) and M. Tech. (Hydrocarbon Engineering) 11 View View
5
IDD
B. Tech. (Chemical Engineering) and M. Tech. (Hydrocarbon Engineering)
11
View
View
6 IDD B. Tech. (Computer Science & Engineering) and M. Tech. (Information Technology) 2 View View
6
IDD
B. Tech. (Computer Science & Engineering) and M. Tech. (Information Technology)
2
View
View
7 IDD B. Tech. (Electrical Engineering) and M.Tech. (Power Electronics) 10 View View
7
IDD
B. Tech. (Electrical Engineering) and M.Tech. (Power Electronics)
10
View
View
8 IDD B. Tech. (Electronics & Communication Engineering) and M. Tech. (Wireless Communication) 15 View View
8
IDD
B. Tech. (Electronics & Communication Engineering) and M. Tech. (Wireless Communication)
15
View
View
9 IDD B. Tech. (Process Engineering) and M.B.A. 9 View View
9
IDD
B. Tech. (Process Engineering) and M.B.A.
9
View
View
10 B.Tech. Biotechnology 14 View View
10
B.Tech.
Biotechnology
14
View
View
11 MSc Biotechnology 1 View View
11
MSc
Biotechnology
1
View
View
12 M.Tech. CAD,CAM & Robotics 4 View View
12
M.Tech.
CAD,CAM & Robotics
4
View
View
13 B.Tech. Chemical Engineering 49 View View
13
B.Tech.
Chemical Engineering
49
View
View
14 IMSc Chemistry 2 View View
14
IMSc
Chemistry
2
View
View
15 B.Tech. Civil Engineering 36 View View
15
B.Tech.
Civil Engineering
36
View
View
16 IDD Civil Engineering with specialisation in Structures 5 View View
16
IDD
Civil Engineering with specialisation in Structures
5
View
View
17 M.Tech. Communication Systems 2 View View
17
M.Tech.
Communication Systems
2
View
View
18 M.Tech. Computer Science & Engineering 36 View View
18
M.Tech.
Computer Science & Engineering
36
View
View
19 B.Tech. Computer Science and Engineering 69 View View
19
B.Tech.
Computer Science and Engineering
69
View
View
20 M.Tech. Electric Drives and Power Electronics 2 View View
20
M.Tech.
Electric Drives and Power Electronics
2
View
View
21 B.Tech. Electrical Engineering 92 View View
21
B.Tech.
Electrical Engineering
92
View
View
22 B.Tech. Electronics & Communication Engineering 66 View View
22
B.Tech.
Electronics & Communication Engineering
66
View
View
23 IMT Geological Technology 12 View View
23
IMT
Geological Technology
12
View
View
24 IMT Geophysical Technology 15 View View
24
IMT
Geophysical Technology
15
View
View
25 MSc M.Sc. Mathematics 1 View View
25
MSc
M.Sc. Mathematics
1
View
View
26 M.Tech. Machine Design Engineering 4 View View
26
M.Tech.
Machine Design Engineering
4
View
View
27 MBA Management and Business Administration 47 View View
27
MBA
Management and Business Administration
47
View
View
28 MURP Master of Urban and Rural Planning 1 View View
28
MURP
Master of Urban and Rural Planning
1
View
View
29 B.Tech. Mechanical Engineering 38 View View
29
B.Tech.
Mechanical Engineering
38
View
View
30 B.Tech. Metallurgical & Materials Engineering 37 View View
30
B.Tech.
Metallurgical & Materials Engineering
37
View
View
31 IDD Metallurgy Dual 7 View View
31
IDD
Metallurgy Dual
7
View
View
32 M.Tech. Micro Electronic and VLSI 4 View View
32
M.Tech.
Micro Electronic and VLSI
4
View
View
33 IMSc Physics 3 View View
33
IMSc
Physics
3
View
View
34 B.Tech. Polymer Science and Technology 1 View View
34
B.Tech.
Polymer Science and Technology
1
View
View
35 M.Tech. Power System Engineering 3 View View
35
M.Tech.
Power System Engineering
3
View
View
36 B.Tech. Production and Industrial Engineering 25 View View
36
B.Tech.
Production and Industrial Engineering
25
View
View
37 M.Tech. Pulp & Paper Engineering 1 View View
37
M.Tech.
Pulp & Paper Engineering
1
View
View
38 M.Tech. RF and Microwave Engineering 2 View View
38
M.Tech.
RF and Microwave Engineering
2
View
View
39 M.Tech. Solid State Electronic Materials 1 View View
39
M.Tech.
Solid State Electronic Materials
1
View
View
40 M.Tech. Structural Dynamics 8 View View
40
M.Tech.
Structural Dynamics
8
View
View
41 M.Tech. Structural Engineering 4 View View
41
M.Tech.
Structural Engineering
4
View
View
42 M.Tech. System and Control 1 View View
42
M.Tech.
System and Control
1
View
View
43 M.Tech. Thermal Engineering 1 View View
43
M.Tech.
Thermal Engineering
1
View
View
44 M.Tech. Transportation Engineering 2 View View
44
M.Tech.
Transportation Engineering
2
View
View

In [61]:
import pandas as pd 
from pandas import DataFrame

In [62]:
rows = driver.find_element_by_tag_name('tbody').find_elements_by_tag_name('tr')
for row in rows:
        k=row.find_elements_by_tag_name('td')
        company.append(k[2].text)
        selected.append(k[3].text)

In [63]:
df = pd.DataFrame({'Company':company,'selected':selected})

In [79]:
df.head()

                                             Company selected
0                                    Applied Geology        2
1                                Applied Mathematics       11
2                          Architecture and Planning       13
3                          Architecture and Planning       10
4  B. Tech. (Chemical Engineering) and M. Tech. (...       11

In [11]:
df.to_csv("selectednum.csv",index=False)

In [65]:
driver.get("https://channeli.in/placement/results/2016/company/")

In [66]:
comp = []
selected2 = []

In [23]:
rows2 = driver.find_element_by_tag_name('tbody').find_elements_by_tag_name('tr')
for row in rows2:
        m=row.find_elements_by_tag_name('td')
        comp.append(m[1].text)
        selected2.append(m[2].text)

In [24]:
df2 = pd.DataFrame({'Company':comp,'Selected':selected2})

In [ ]:
# df2.to_csv("selectedcomp1.csv",index=False)