In [1]:
#Initial imports 
import numpy as np
import pandas as pd 
from pandas import DataFrame, Series
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
%matplotlib inline
from IPython.core.interactiveshell import InteractiveShell #Show all consecutive outputs
InteractiveShell.ast_node_interactivity = "all"

In [2]:
#Removes all unnecessary warnings by Python
import warnings
warnings.filterwarnings('ignore')

In [3]:
from matplotlib import rcParams
import matplotlib.cm as cm
import matplotlib as mpl

#colorbrewer2 Dark2 qualitative color table
dark2_colors = [(0.10588235294117647, 0.6196078431372549, 0.4666666666666667),
                (0.8509803921568627, 0.37254901960784315, 0.00784313725490196),
                (0.4588235294117647, 0.4392156862745098, 0.7019607843137254),
                (0.9058823529411765, 0.1607843137254902, 0.5411764705882353),
                (0.4, 0.6509803921568628, 0.11764705882352941),
                (0.9019607843137255, 0.6705882352941176, 0.00784313725490196),
                (0.6509803921568628, 0.4627450980392157, 0.11372549019607843)]

rcParams['figure.figsize'] = (14, 6)
rcParams['figure.dpi'] = 250
rcParams['axes.color_cycle'] = dark2_colors
rcParams['lines.linewidth'] = 3
rcParams['axes.facecolor'] = 'white'
rcParams['font.size'] = 25
rcParams['patch.edgecolor'] = 'white'
rcParams['patch.facecolor'] = dark2_colors[0]
rcParams['font.family'] = 'StixGeneral'

In [4]:
#Show all the columns 
pd.set_option('display.max_columns',None)

In [5]:
demogy = pd.read_excel('exl_data_Y.xlsx',sheetname='Demographic Data')

In [6]:
demogv = pd.read_excel('exl_data_val.xlsx',sheetname='Demographic Data')

In [7]:
# demogy.head()
# demogv.head()

In [8]:
del demogv['Churn']

In [9]:
demogv.isnull().sum()
demogy.isnull().sum()
demogy.shape
demogv.shape

Account Number                       0
Commence Date                        2
Address                             17
Scheme                               0
Staus                                0
Gender                             671
Zone                                 0
Salequip                             0
Age                                947
Equipment Warranty                 224
Salary Slab                        657
Professional Info                  657
Age of Home                        657
Equipment Warranty Expiry Date     224
Churn Date                        4986
dtype: int64

Account Number                       0
Commence Date                        3
Address                            386
Scheme                               0
Staus                                0
Gender                            1368
Zone                                 0
Eqipsale                             0
Age                               2013
Equipment Warranty                 408
Salary Slab                       1351
Professional Info                 1351
Age of Home                       1351
Equipment Warranty Expiry Date     408
Churn                                0
Churn Date                        9460
dtype: int64

(9966, 16)

(4986, 15)

In [10]:
9966+4986

14952

In [11]:
demogy['Equipment Warranty'].fillna('Three Full Years',inplace='True')

In [12]:
demogv['Equipment Warranty'].fillna('Three Full Years',inplace='True')

In [13]:
demogy['Gender'].fillna('other',inplace=True)
demogv['Gender'].fillna('other',inplace=True)

In [20]:
demogy.isnull().sum()
demogy.isnull().sum()

Account Number                       0
Commence Date                        3
Address                            386
Scheme                               0
Staus                                0
Gender                               0
Zone                                 0
Eqipsale                             0
Age                                  0
Equipment Warranty                   0
Salslab                              0
profinfo                             0
agehome                              0
Equipment Warranty Expiry Date     408
Churn                                0
Churn Date                        9460
dtype: int64

Account Number                       0
Commence Date                        3
Address                            386
Scheme                               0
Staus                                0
Gender                               0
Zone                                 0
Eqipsale                             0
Age                                  0
Equipment Warranty                   0
Salslab                              0
profinfo                             0
agehome                              0
Equipment Warranty Expiry Date     408
Churn                                0
Churn Date                        9460
dtype: int64

In [15]:
demogy['Professional Info'].fillna(0.0,inplace=True)
demogv['Professional Info'].fillna(0.0,inplace=True)

In [16]:
demogy = demogy.rename(columns={'Salary Slab':'Salslab','Age of Home':'agehome','Professional Info': 'profinfo'})
demogv = demogv.rename(columns={'Salary Slab':'Salslab','Age of Home':'agehome','Professional Info': 'profinfo'})

In [17]:
#Alloting median of each scheme age
demogy.loc[demogy.Age.isnull(), 'Age'] = demogy.groupby('Scheme').Age.transform('median')
demogv.loc[demogv.Age.isnull(), 'Age'] = demogv.groupby('Scheme').Age.transform('median')

In [18]:
#Alloting median of each scheme age of home
demogy.loc[demogy.agehome.isnull(), 'agehome'] = demogy.groupby('Scheme').agehome.transform('median')
demogv.loc[demogv.agehome.isnull(), 'agehome'] = demogv.groupby('Scheme').agehome.transform('median')

In [19]:
#Alloting median of each scheme age
demogy.loc[demogy.Salslab.isnull(), 'Salslab'] = demogy.groupby('Scheme').Salslab.transform('median')
demogv.loc[demogv.Salslab.isnull(), 'Salslab'] = demogv.groupby('Scheme').Salslab.transform('median')

In [21]:
demogy.groupby('Scheme').agg(['count','mean','median'])

         Age                   Salslab                  profinfo            \
       count       mean median   count      mean median    count      mean
Scheme
CHC      774  52.974160   54.0     774  4.188630    4.0      774  3.095607
CNN      916  53.348253   54.0     916  4.210699    4.0      916  3.218341
ESS      111  51.063063   52.0     111  4.216216    4.0      111  2.270270
KLA      968  46.404959   46.0     968  4.461777    4.0      968  2.254132
MXX      299  48.876254   49.0     299  4.525084    4.0      299  2.541806
PMM       15  56.733333   54.0      15  4.533333    4.0       15  4.333333
POP      464  51.586207   52.0     464  4.946121    5.0      464  3.681034
PPL     1815  48.764187   49.0    1815  4.182369    4.0     1815  2.656749
PRM     1397  48.375089   49.0    1397  4.227631    4.0     1397  3.000716
PRP      444  47.754505   47.5     444  4.439189    4.0      444  3.013514
PRR      442  47.506787   47.0     442  4.497738    4.0      442  2.947964
PWM      296  51.841216   51.5     296  5.216216    5.0      296  3.354730
PWP      201  56.810945   57.0     201  5.199005    5.0      201  5.238806
PWR     1824  51.971491   53.0    1824  4.523575    4.0     1824  3.648026

              agehome                   Churn
       median   count       mean median count      mean median
Scheme
CHC       0.0     774  14.617571   17.0   774  0.049096      0
CNN       0.0     916  14.814410   17.0   916  0.051310      0
ESS       0.0     111  12.468468   12.0   111  0.153153      0
KLA       0.0     968  12.309917   12.0   968  0.039256      0
MXX       0.0     299  12.464883   12.0   299  0.090301      0
PMM       2.0      15  15.600000   17.0    15  0.066667      0
POP       0.0     464  15.698276   17.0   464  0.045259      0
PPL       0.0    1815  12.750964   12.0  1815  0.053994      0
PRM       0.0    1397  12.761632   12.0  1397  0.054402      0
PRP       0.0     444  13.328829   12.0   444  0.060811      0
PRR       0.0     442  13.674208   17.0   442  0.056561      0
PWM       0.0     296  15.331081   17.0   296  0.023649      0
PWP       0.0     201  16.810945   21.0   201  0.019900      0
PWR       0.0    1824  15.735746   17.0  1824  0.043860      0

In [22]:
demogy.groupby('Gender').agg(['count','mean','median'])

         Age                   Salslab                  profinfo            \
       count       mean median   count      mean median    count      mean
Gender
Female  3963  49.904365   50.0    3963  4.400707    4.0     3963  3.705021
Male    4635  50.294822   50.0    4635  4.507659    4.0     4635  3.448328
other   1368  50.305921   49.0    1368  4.067982    4.0     1368  0.000000

              agehome                   Churn
       median   count       mean median count      mean median
Gender
Female    0.0    3963  13.958365   17.0  3963  0.051224      0
Male      0.0    4635  13.923409   17.0  4635  0.045307      0
other     0.0    1368  13.983187   12.0  1368  0.067982      0

In [23]:
demogy.groupby('Staus').agg(['count','mean','median'])

         Age                   Salslab                  profinfo            \
       count       mean median   count      mean median    count      mean
Staus
Closed   368  49.625000   49.0     368  4.076087    4.0      368  2.054348
Open    9598  50.160867   50.0    9598  4.417379    4.0     9598  3.116274

              agehome                   Churn
       median   count       mean median count      mean median
Staus
Closed    0.0     368  12.899457   12.0   368  0.364130      0
Open      0.0    9598  13.985622   17.0  9598  0.038758      0

In [24]:
demogy.groupby('Zone').agg(['count','mean','median'])

           Age                   Salslab                  profinfo            \
         count       mean median   count      mean median    count      mean
Zone
Eastern   4122  50.033964   50.0    4122  4.389374    4.0     4122  3.311257
Northern  4409  49.705602   49.0    4409  4.303470    4.0     4409  2.886369
Southern   227  50.790749   50.0     227  4.889868    4.0      227  3.167401
Western   1208  51.973924   51.5    1208  4.735927    4.0     1208  2.956954

                agehome                   Churn
         median   count       mean median count      mean median
Zone
Eastern     0.0    4122  14.134886   17.0  4122  0.053615      0
Northern    0.0    4409  13.866863   12.0  4409  0.052166      0
Southern    0.0     227  12.559471   12.0   227  0.057269      0
Western     0.0    1208  13.846854   12.0  1208  0.034768      0

In [25]:
demogy.groupby('Eqipsale').agg(['count','mean','median'])

              Age                   Salslab                  profinfo  \
            count       mean median   count      mean median    count
Eqipsale
BOUGHT       1003  51.918744   52.0    1003  4.688933    4.0     1003
RENTED       8918  49.917134   49.0    8918  4.371832    4.0     8918
Second Hand    43  55.127907   54.0      43  4.534884    4.0       43
Unknown         2  50.000000   50.0       2  6.000000    6.0        2

                             agehome                   Churn
                 mean median   count       mean median count      mean median
Eqipsale
BOUGHT       3.319043    0.0    1003  15.022931   17.0  1003  0.051844      0
RENTED       3.053824    0.0    8918  13.811056   12.0  8918  0.050796      0
Second Hand  2.209302    0.0      43  16.441860   17.0    43  0.023256      0
Unknown      4.000000    4.0       2  19.500000   19.5     2  0.000000      0

In [26]:
pd.crosstab(demogy.Scheme,demogy.Salslab,margins=True)

Salslab,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,All
Scheme,,,,,,,,,,,,,,
CHC,40,47,159,269,100,103,29,14,8,5,0,0,0,774
CNN,38,44,222,291,134,126,35,11,11,3,0,0,1,916
ESS,6,9,24,34,13,14,6,2,2,0,1,0,0,111
KLA,55,36,203,302,115,142,50,25,23,7,4,1,5,968
MXX,10,10,65,96,33,53,14,6,8,3,0,0,1,299
PMM,0,0,7,3,0,2,1,2,0,0,0,0,0,15
POP,15,14,71,87,121,88,33,10,16,4,0,2,3,464
PPL,92,96,380,692,190,231,66,36,20,7,1,0,4,1815
PRM,50,74,329,473,179,185,61,25,16,4,0,0,1,1397
PRP,24,21,73,147,67,61,31,10,7,0,1,0,2,444
PRR,23,17,88,135,53,72,32,10,5,3,0,1,3,442
PWM,8,5,41,52,69,64,27,14,8,2,2,1,3,296
PWP,9,6,29,33,41,43,14,8,10,3,2,1,2,201
PWR,74,63,352,579,254,305,105,35,34,11,2,4,6,1824
All,444,442,2043,3193,1369,1489,504,208,168,52,13,10,31,9966

In [27]:
#AFMVI = After Missing Value Imputation of demographic data
demogy.to_csv('AFMVIM.csv',index=False)
demogv.to_csv('AFMVIV.csv',index=False)